#!/bin/sh
set -eu

PROJECT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$PROJECT_DIR"

ENV_FILE="${ENV_FILE:-.env}"
ACTION="${1:-up}"

find_docker() {
  if command -v docker >/dev/null 2>&1; then
    command -v docker
    return
  fi

  if [ -x /Applications/Docker.app/Contents/Resources/bin/docker ]; then
    printf '%s\n' /Applications/Docker.app/Contents/Resources/bin/docker
    return
  fi

  printf '%s\n' "docker"
}

DOCKER_BIN=$(find_docker)

compose() {
  if "$DOCKER_BIN" compose version >/dev/null 2>&1; then
    "$DOCKER_BIN" compose "$@"
    return
  fi

  if command -v docker-compose >/dev/null 2>&1; then
    docker-compose "$@"
    return
  fi

  echo "Docker Compose is not available. Please install Docker with Compose." >&2
  exit 1
}

random_hex() {
  bytes="$1"

  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$bytes"
    return
  fi

  od -An -N "$bytes" -tx1 /dev/urandom | tr -d ' \n'
}

env_value() {
  key="$1"

  if [ ! -f "$ENV_FILE" ]; then
    return
  fi

  awk -F= -v key="$key" '
    $1 == key {
      sub(/^[^=]*=/, "")
      value = $0
    }
    END {
      if (value != "") {
        print value
      }
    }
  ' "$ENV_FILE"
}

append_env() {
  key="$1"
  value="$2"

  if [ -z "$(env_value "$key")" ]; then
    printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
  fi
}

is_interactive() {
  [ -t 0 ] && [ -t 1 ]
}

prompt_admin_email() {
  default_email="${ADMIN_EMAIL:-admin@example.com}"

  if ! is_interactive; then
    printf '%s\n' "$default_email"
    return
  fi

  printf 'Admin email [%s]: ' "$default_email" >&2
  IFS= read -r email
  printf '%s\n' "${email:-$default_email}"
}

read_secret() {
  if command -v stty >/dev/null 2>&1; then
    stty -echo
    IFS= read -r value
    stty echo
    printf '\n' >&2
    printf '%s\n' "$value"
    return
  fi

  IFS= read -r value
  printf '%s\n' "$value"
}

prompt_admin_password() {
  if [ -n "${ADMIN_PASSWORD:-}" ]; then
    printf '%s\n' "$ADMIN_PASSWORD"
    return
  fi

  if ! is_interactive; then
    echo "ADMIN_PASSWORD is required. Run interactively, or use:" >&2
    echo "ADMIN_PASSWORD='your-password' ./deploy.sh" >&2
    exit 1
  fi

  while :; do
    printf 'Set initial admin password (at least 8 chars): ' >&2
    password=$(read_secret)
    printf 'Repeat admin password: ' >&2
    password_confirm=$(read_secret)

    if [ "$password" != "$password_confirm" ]; then
      echo "Passwords do not match. Try again." >&2
      continue
    fi

    if [ "${#password}" -lt 8 ]; then
      echo "Password must be at least 8 characters." >&2
      continue
    fi

    printf '%s\n' "$password"
    return
  done
}

ensure_env() {
  if [ ! -f "$ENV_FILE" ]; then
    umask 077

    postgres_user="maleme"
    postgres_db="maleme"
    postgres_password=$(random_hex 24)
    app_secret=$(random_hex 32)
    admin_email=$(prompt_admin_email)
    admin_password=$(prompt_admin_password)
    app_port="6088"
    database_url="postgresql://${postgres_user}:${postgres_password}@postgres:5432/${postgres_db}?schema=public"

    cat > "$ENV_FILE" <<EOF
# Generated by ./deploy.sh. Do not commit this file.
POSTGRES_USER=${postgres_user}
POSTGRES_PASSWORD=${postgres_password}
POSTGRES_DB=${postgres_db}
DATABASE_URL=${database_url}
APP_SECRET=${app_secret}
ADMIN_EMAIL=${admin_email}
ADMIN_PASSWORD=${admin_password}
APP_PORT=${app_port}
EOF
  else
    postgres_user=$(env_value POSTGRES_USER)
    postgres_db=$(env_value POSTGRES_DB)
    postgres_password=$(env_value POSTGRES_PASSWORD)
    app_secret=$(env_value APP_SECRET)
    admin_email=$(env_value ADMIN_EMAIL)
    admin_password=$(env_value ADMIN_PASSWORD)
    app_port=$(env_value APP_PORT)

    [ -n "$postgres_user" ] || postgres_user="maleme"
    [ -n "$postgres_db" ] || postgres_db="maleme"
    [ -n "$postgres_password" ] || postgres_password=$(random_hex 24)
    [ -n "$app_secret" ] || app_secret=$(random_hex 32)
    [ -n "$admin_email" ] || admin_email=$(prompt_admin_email)
    [ -n "$admin_password" ] || admin_password=$(prompt_admin_password)
    [ -n "$app_port" ] || app_port="6088"

    append_env POSTGRES_USER "$postgres_user"
    append_env POSTGRES_PASSWORD "$postgres_password"
    append_env POSTGRES_DB "$postgres_db"
    append_env DATABASE_URL "postgresql://${postgres_user}:${postgres_password}@postgres:5432/${postgres_db}?schema=public"
    append_env APP_SECRET "$app_secret"
    append_env ADMIN_EMAIL "$admin_email"
    append_env ADMIN_PASSWORD "$admin_password"
    append_env APP_PORT "$app_port"
  fi
}

print_ready() {
  admin_email=$(env_value ADMIN_EMAIL)
  app_port=$(env_value APP_PORT)

  echo
  echo "Maleme is running."
  echo "URL: http://localhost:${app_port:-6088}"
  echo "Admin email: ${admin_email:-admin@example.com}"
  echo "Admin password: the one you set in ${ENV_FILE}"
}

usage() {
  cat <<EOF
Usage:
  ./deploy.sh          Generate .env if needed and start the app
  ./deploy.sh up       Same as above
  ./deploy.sh logs     Follow app logs
  ./deploy.sh ps       Show container status
  ./deploy.sh stop     Stop containers
EOF
}

case "$ACTION" in
  up|start)
    ensure_env
    compose up --build -d
    print_ready
    ;;
  logs)
    compose logs -f app
    ;;
  ps)
    compose ps
    ;;
  stop)
    compose down
    ;;
  help|--help|-h)
    usage
    ;;
  *)
    usage
    exit 1
    ;;
esac
